# -*- coding: utf-8 -*-
"""Analisis_Data_Bike_Sharing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ton_qa_SDCveVzOXFKQnzxz8DnA4VGBp

# Proyek Analisis Data: Bike-Sharing
- **Nama:** Nuryana Saepul Ramdan
- **Email:** nuryanasaepulramdan@gmail.com
- **ID Dicoding:** nuryanasaepulramdan

## Menentukan Pertanyaan Bisnis

- Berapa jumlah pengguna sepeda dalam setiap musim?
- Bagaimana pengaruh cuaca terhadap jumlah pengguna sepeda?
- Pada bulan apa jumlah pengguna sepeda tertinggi dan terendah?

## Import Semua Packages/Library yang Digunakan
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data

Memuat tabel day
"""

day_df = pd.read_csv("https://raw.githubusercontent.com/nsfis21/bike-sharing/refs/heads/main/day.csv")
day_df.head()

"""**Insight:**
- Pada proses ini, kita memuat semua data yang akan dianalisis.
- Dari tabel day pada dataset bike-sharing, kita memperoleh informasi mengenai indeks rekaman, tanggal, musim, tahun, hari kerja, hari libur, cuaca, kelembapan, kecepatan angin, bulan, pengguna kasual, terdaftar, dan total  pengguna sepeda.

### Assessing Data

Menilai Data day_df
"""

day_df.info()

"""Menampilkan ringkasan parameter statistik dari data day_df"""

day_df.describe()

"""**Insight:**
- Dalam proses ini, ditemukan kesalahan tipe data dalam tabel dteday, yang memuat informasi mengenai tanggal dan tahun penyewaan sepeda.
- Sebelumnya, tabel dteday bertipe object, seharusnya datetime.

### Cleaning Data

Menangani kesalahan tipe data pada kolom dteday
"""

datetime_columns = ["dteday"]
for column in datetime_columns:
    day_df[column] = pd.to_datetime(day_df[column])

day_df.info()

"""**Insight:**
- Pada tahap ini, kita memperbaiki setiap kesalahan dalam data.
- Pada dat diatas, kita memperbaiki kesalahan tipe data pada tabel dteday.

## Exploratory Data Analysis (EDA)

### Explorasi Data day_df
"""

day_df.describe(include="all")

"""Menampilkan jumlah pengguna sepeda untuk tiap kategori berdasarkan musim"""

day_df.groupby(by="season").agg({
    "casual": "sum",
    "registered": "sum",
    "cnt": "sum"
})

"""Menampilkan jumlah pengguna sepeda berdasarkan faktor cuaca, suhu, kelembapan, dan kecepatan angin."""

day_df.groupby(by=["weathersit", "temp", "atemp", "hum", "windspeed"]).agg({
    "casual": "sum",
    "registered": "sum",
    "cnt": "sum"
})

"""Menampilkan hubungan antara jumlah pengguna sepeda berdasarkan kategori hari libur dan hari kerja"""

day_df.groupby(by=["holiday", "weekday", "workingday"]).agg({
    "casual": "sum",
    "registered": "sum",
    "cnt": "sum"
})

"""Menampilkan jumlah pengguna sepeda untuk tiap-tiap bulan."""

day_df.groupby(by="mnth").agg({
    "casual": "sum",
    "registered": "sum",
    "cnt": "sum"
})

"""Menampilkan jumlah pengguna sepeda di tahun 2011 an 2012"""

day_df.groupby(by="yr").agg({
    "casual": "sum",
    "registered": "sum",
    "cnt": "sum"
})

"""**Insight:**
- Pada tahap ini, kita mengeksplorasi data yang ada, untuk menemukan informasi menarik yang dapat di analisis.
- Pada data diatas, kita menganalisis informasi mengenai jumlah pengguna sepeda dari beberapa parameter yang tersedia, seperti bulan, musim, dan lain-lain.

## Visualization & Explanatory Analysis

### Pertanyaan 1: Berapa jumlah pengguna sepeda dalam setiap musim?
"""

day_df.groupby(by="season").agg({
    "casual": "sum",
    "registered": "sum",
    "cnt": "sum"
})

season_data = {1: "Spring", 2: "Summer", 3: "Fall", 4: "Winter"}
day_df["name_season"] = day_df["season"].map(season_data)
data_season= day_df.groupby("name_season").agg({
    "casual": "sum",
    "registered": "sum",
    "cnt": "sum"
}).reset_index()
plt.figure(figsize=(6, 3))
sns.barplot(
    x="name_season", y="cnt", data=data_season)
plt.title("Count of bicycle rentals based on season", fontsize=11)
plt.ylabel("Count of Total Rental", fontsize=10)
plt.xlabel("Season", fontsize=10)
plt.show()

"""### Pertanyaan 2: Bagaimana pengaruh cuaca terhadap jumlah pengguna sepeda?"""

day_df.groupby(by="weathersit").agg({
    "casual": "sum",
    "registered": "sum",
    "cnt": "sum"
})

weather_data = {1:"Clear & Few clouds", 2:"Mist & Cloudy", 3:"Light Snow & Light Rain", 4:"Heavy Rain & Ice"}
day_df["name_weather"] = day_df["weathersit"].map(weather_data)
plt.figure(figsize=(6, 3))
sns.boxplot(x="name_weather", y="cnt", data=day_df)
plt.xlabel("Weather")
plt.ylabel("Total Bike Rentals")
plt.title("Distribution of Bike Rentals by Weather")
plt.xticks(rotation=45)
plt.show()

"""### Pertanyaan 3: Pada bulan apa jumlah pengguna sepeda tertinggi dan terendah?


"""

day_df.groupby(by="mnth").agg({
    "casual": "sum",
    "registered": "sum",
    "cnt": "sum"
})

mnth_data = day_df.groupby("mnth").agg({
    "casual": "sum",
    "registered": "sum",
    "cnt": "sum"
}).reset_index()
mnths = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
mnth_data["mnth_name"] = mnths

plt.figure(figsize=(6, 3))
plt.plot(mnth_data["mnth_name"], mnth_data["casual"], label="Casual", marker = "o")
plt.plot(mnth_data["mnth_name"], mnth_data["registered"], label="Registered", marker = "o")
plt.plot(mnth_data["mnth_name"], mnth_data["cnt"], label="Total", marker = "o")
plt.title("Count of bicycle rentals based on month", fontsize=11)
plt.ylabel("Count of Total Rental", fontsize=10)
plt.xlabel("Month", fontsize=10)
plt.legend()
plt.show()

"""### Pertanyaan 4: Bagaimana pola sebaran pengguna sepeda di tahun 2011 dan 2012?"""

day_df.groupby(by="yr").agg({
    "cnt": "sum"
})

yr_label = {0: "2011", 1: "2012"}
day_df["year"] = day_df["yr"].map(yr_label)
data_yr = day_df.groupby("dteday").agg({
    "cnt": "sum"
}).reset_index()
plt.figure(figsize=(10, 5))
day_df["dteday"] = pd.to_datetime(day_df["dteday"])
sns.lineplot(x="dteday", y="cnt", data=day_df, hue="year", palette="coolwarm")
plt.xlabel("Date")
plt.ylabel("Total Bike Rentals")
plt.title("Trend of Bike Rentals over Time")
plt.xticks(rotation=45)
plt.show()

"""**Insight:**
- Pada tahap ini, kita melakukan eksplanasi data untuk menjawab semua pertanyaan bisnis yang telah diajukan.
- Kemudian kita melakukan visualisasi data untuk menampilkan hasil analisis dalam bentuk visual.

## Conclusion

- Jumlah pengguna sepeda paling banyak pada musim gugur, diikuti dengan musim panas, dingin, dan paling sedikit musim semi.
- Cuaca berpengaruh terhadap jumlah pengguna sepeda, rata-rata orang sewa sepeda pada saat cuaca cerah, sedikit berawan, dan berawan sebagian. Dari hasil analisis diatas, tidak ada orang yang bersepeda pada saat hujan lebat, badai petir, kabut, dan salju.
- Untuk pengguna kasual, jumlah pengguna sepeda tertinggi ada di bulan juli sedangkan terendah di bulan januari. Kemudian, untuk pengguna terdaftar, jumlah pengguna sepeda tertinggi ada di bulan agustus, sedangkan terendah di bulan januari. Terakhir, untuk pengguna sepeda secara total, pengguna tertinggi di bulan agustus, dan terendah di bulan januari.
- Trend penyewa sepeda tertinggi terjadi pada tahun 2012. Di kedua tahun tersebut, trend sewa sepeda meningkat di tengah bulan antara juni-september, kemudian menurun di setiap awal dan akhir bulan.
"""